#!/bin/bash

function show_help () {
cat <<HEREDOC

File:
    checksum.sh
    
Version:
    9 okt 2019 15:40:36

By:
    Johan.Nylander\@nbis.se

Usage:
    checksum.sh CHECKSUMS

Description:
    Verify checksums generated by the sum command.
    Will only check files found both in the
    CHECKSUMS file, and on disk.
    Prints FAIL to STDOUT if sums doesn't match.
    If the verbose (-v) option is used, more
    information is printed about all files in
    the CHECKSUMS file.
    May not work for filenames with spaces.

Options:
    -?, -h  -- show this help
    -v      -- be more verbose

HEREDOC
}

if ! hash sum 2>/dev/null ; then
  echo "Error: program sum is not found. Aborting"
  exit 1
fi

verbose=0

while getopts "h?v" opt; do
  case "$opt" in
  h|\?)
    show_help
    exit 0
    ;;
  v)  verbose=1
    ;;
  esac
done

shift $((OPTIND-1))

if [ ! -e "$1" ] ; then
    echo "Error: No input file?"
    show_help
    exit 0
fi

if [ "$verbose" -eq 1 ]; then
  echo "Checking $1 file in $PWD:"
  echo ""
fi

while read -r line ; do 
  f=$(echo "$line" | sed "s/^.* //")
  if [ -e "$f" ]; then 
    ss=$(sum "$f")
    if [ "$line"  == "$ss $f" ]; then
      if [ "$verbose" -eq 1 ]; then
        echo "OK   sum ($ss): $f"
      fi
    else echo "FAIL sum ($ss): $f"
    fi
  else
    if [ "$verbose" -eq 1 ]; then
      echo "SKIP file  (not found): $f"
    fi
  fi
done < "$1"

if [ "$verbose" -eq 1 ]; then
    echo ""
  echo 'Done with script' "$0"
fi

